name: Deploy

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Clean
      uses: heowc/action-hexo@master
      with:
        args: clean
    - name: Generate
      uses: heowc/action-hexo@master
      with:
        args: generate
    - name: Deploy
      uses: heowc/action-hexo@master
      env:
        EMAIL: 4468525+huntertran@users.noreply.github.com
        NAME: Tuan Tran Van
      with:
        args: deploy
